USE Zensar_DB
--Q1
SELECT TOP 1 * FROM EMP
WHERE DEPTNO = 30
ORDER BY HIREDATE DESC

SELECT * FROM emp 
WHERE HIREDATE = (SELECT min(HIREDATE) 
				  FROM emp 
				  WHERE DEPTNO=30)

--Q2
SELECT * FROM EMP
WHERE SAL < (SELECT AVG(SAL) 
			 FROM EMP
			 WHERE JOB = 'Salesman')
and JOB != 'salesman'

--Q3

SELECT * FROM EMP
WHERE SAL = (SELECT MAX(SAL)
			 FROM EMP
			 WHERE JOB = 'CLERK')

--Q4
	SELECT ENAME, HIREDATE ,SAL FROM EMP
	WHERE (SAL = (SELECT SAL
				 FROM EMP
				 WHERE ENAME = 'SCOTT')
	OR COMM = (SELECT COMM
				 FROM EMP
				 WHERE ENAME = 'SCOTT'))
	AND ENAME <> 'SCOTT'

SELECT ENAME, HIREDATE ,SAL FROM EMP
WHERE (SAL = (SELECT SAL
			 FROM EMP
			 WHERE ENAME = 'SCOTT')
OR COMM = (SELECT COMM
			 FROM EMP
			 WHERE ENAME = 'SCOTT'))
AND ENAME != 'SCOTT'


--Q5

SELECT * FROM EMP
SELECT E.ENAME,D.DNAME	
FROM EMP E , DEPT D
WHERE SAL >(SELECT SAL
			FROM EMP
			WHERE ENAME = 'mARTIN')
AND E.DEPTNO = D.DEPTNO


--Q6
SELECT E1.ENAME,E2.JOB,E1.SAL,E2.Maximum,E2.Minimum,E2.Average
FROM EMP E1 JOIN (SELECT JOB, MAX(SAL) AS 'Maximum', MIN(SAL) AS 'Minimum', AVG(SAL) as 'Average'
FROM EMP GROUP BY JOB) as e2
ON E1.JOB = E2.JOB
ORDER BY JOB

--Q7
SELECT * FROM EMP
WHERE SAL > (SELECT AVG(SAL)
			 FROM EMP
			 WHERE JOB = 'SALESMAN')
AND JOB <> 'MANAGER'

--Q8

SELECT E1.ENAME,E1.DEPTNO,E1.SAL 'Salary',E2.Maximum,(E2.Maximum-E1.SAL) AS 'Difference' 
FROM EMP E1 LEFT JOIN (SELECT TOP 3 DEPTNO, MAX(SAL) AS 'Maximum' FROM EMP GROUP BY DEPTNO ORDER BY Maximum DESC) as e2
ON E1.DEPTNO = E2.DEPTNO
ORDER BY E1.DEPTNO, E2.Maximum DESC


--Q9
SELECT D.DNAME
FROM EMP E, DEPT D
WHERE E.SAL = (SELECT MAX(SAL)
			 FROM EMP)
AND E.DEPTNO = D.DEPTNO
GROUP BY D.DNAME 